from annotations import column_name

columns: list[column_name] = [
    'Дата',
    'Время',
    'Название матча',
    'Название лиги',
    'Счет матча',
    'Счет первого тайма',
    'Счет второго тайма',
    'Средний коэффициент на домашнюю команду',
    'Средний коэффициент на ничью',
    'Средний коэффициент на гостевую команду',
    'Минута, на которой был забит первый гол',
    '10Bet',
    '188BET',
    '1xBet',
    '888sport',
    'bet-at-home',
    'bet365',
    'Betclic',
    'Betfair',
    'Betsafe',
    'Betsson',
    'BetVictor',
    'Betway',
    'bwin',
    'ComeOn',
    'Interwetten',
    'Pinnacle',
    'SBOBET',
    'Unibet',
    'William Hill',
    'youwin',
    'Betfair Exchange',
    'Максимальный коэффициент на победу фаворита'
]
